# ==================== PREGUNTAS OFICIALES ICFES ====================
# Extraídas del cuadernillo "Saber 11, 2026-1, Primera Sesión" (Icfes),
# subido por el usuario. Cada pregunta conserva el número original del
# cuadernillo en el campo "num_original" para poder rastrearla si hace falta
# verificar algo contra el PDF fuente.
#
# Este archivo se organiza igual que preguntas.py: un diccionario por área,
# con listas de preguntas. Se importa y se fusiona con el banco propio en
# preguntas.py.

FUENTE_2026_1 = "ICFES Saber 11 · 2026-1"

MATEMATICAS_OFICIALES = [
    {
        "num_original": 1,
        "tema": "Promedio (media aritmética)",
        "pregunta": "En una entrevista realizada a siete mujeres, madres de familia, se les preguntó a qué edad tuvieron su primer hijo (tabla). A partir de la información suministrada, ¿cuál es el promedio de las edades?",
        "opciones": ["18", "22", "24", "28"],
        "correcta": "24",
        "fuente": FUENTE_2026_1,
        "visual": {
            "tipo": "tabla",
            "columnas": ["Madre", "Edad (años)"],
            "datos": [[1, 21], [2, 26], [3, 20], [4, 21], [5, 22], [6, 28], [7, 30]],
        },
    },
    {
        "num_original": 2,
        "tema": "Porcentajes e impuestos",
        "pregunta": "Una aerolínea ofrece vuelos nacionales con tarifas distintas según el día (tabla), aclarando que se debe agregar un impuesto del 12 % o 19 % según la temporada del año. Un usuario compra 5 tiquetes para viajar el día jueves y 2 tiquetes para viajar el día sábado, usando la fórmula: Valor total a pagar = (5 × 80.000 + 2 × 150.000)(1 + y), donde y es el porcentaje del impuesto. Sobre el valor total a pagar, ¿cuál de las siguientes afirmaciones es verdadera?",
        "opciones": [
            "Es posible calcular el valor total a pagar, ya que se aplica el impuesto del 12 % a los tiquetes comprados para el día jueves y el impuesto del 19 % a los tiquetes para el día sábado.",
            "No es posible calcular el valor total a pagar, ya que el impuesto del 12 % y 19 % dependen de la temporada del año, y esta se desconoce.",
            "Es posible calcular el valor total a pagar, ya que se ejecuta la multiplicación entre la cantidad de tiquetes comprados para cada día y el valor respectivo.",
            "No es posible calcular el valor total a pagar, ya que falta conocer la tarifa correspondiente para asignar el valor de los tiquetes para el día jueves y sábado.",
        ],
        "correcta": "No es posible calcular el valor total a pagar, ya que el impuesto del 12 % y 19 % dependen de la temporada del año, y esta se desconoce.",
        "fuente": FUENTE_2026_1,
        "visual": {
            "tipo": "tabla",
            "columnas": ["", "Costo lunes, martes, miércoles o jueves", "Costo viernes, sábado o domingo"],
            "datos": [["Trayecto nacional", "$80.000", "$150.000"]],
        },
    },
    {
        "num_original": 3,
        "tema": "Diagramas de Venn y tablas de frecuencia",
        "pregunta": "Un laboratorio aplicó un tratamiento médico a 60 pacientes y registró en un diagrama de Venn los tres efectos secundarios que padecieron algunos de ellos (dolor de cabeza, mareo, náuseas), con las cantidades en cada región. Luego, un médico registró la información en una tabla con el total de pacientes por cada efecto secundario. ¿Es válida la información que registró el médico en la tabla?",
        "opciones": [
            "No, porque en el diagrama se evidencia que el efecto secundario que más presentaron los pacientes fue el de náuseas.",
            "Sí, porque la cantidad de pacientes que presentó cada síntoma, según la tabla, coincide con la cantidad de pacientes que indica el diagrama.",
            "Sí, porque la cantidad de pacientes a los que se les aplicó el tratamiento, según el diagrama, coincide con la suma de las frecuencias que se presentan en la tabla.",
            "No, porque falta tener en cuenta la cantidad de pacientes que presentaron los tres efectos secundarios.",
        ],
        "correcta": "Sí, porque la cantidad de pacientes que presentó cada síntoma, según la tabla, coincide con la cantidad de pacientes que indica el diagrama.",
        "fuente": FUENTE_2026_1,
        "visual": [
            {
                "tipo": "tabla",
                "columnas": ["Región del diagrama de Venn", "Cantidad de pacientes"],
                "datos": [
                    ["Solo dolor de cabeza", 10],
                    ["Dolor de cabeza y mareo", 8],
                    ["Solo mareo", 5],
                    ["Dolor de cabeza y náuseas", 6],
                    ["Los tres síntomas", 1],
                    ["Solo náuseas", 15],
                    ["Mareo y náuseas", 15],
                ],
            },
            {
                "tipo": "tabla",
                "columnas": ["Efecto secundario", "Cantidad de pacientes (según la tabla del médico)"],
                "datos": [["Dolor de cabeza", 24], ["Náuseas", 22], ["Mareo", 14]],
            },
        ],
    },
    {
        "num_original": 4,
        "tema": "Combinatoria",
        "pregunta": "En una clase de inglés hay 6 estudiantes: 4 mujeres y 2 hombres. El profesor quiere conformar grupos de 3 estudiantes. En una tabla, X, Y, Z y W representan la cantidad de formas de escoger un grupo con la característica: Grupo 1 = tres hombres, Grupo 2 = una mujer y dos hombres, Grupo 3 = dos mujeres y un hombre, Grupo 4 = tres mujeres. ¿Cuáles valores se deben conocer para determinar la cantidad total de formas que hay para escoger un grupo de 3 estudiantes en donde, al menos, uno de ellos sea hombre?",
        "opciones": ["Solamente Z.", "Solamente Z y W.", "Solamente X.", "Solamente Y y Z."],
        "correcta": "Solamente Y y Z.",
        "fuente": FUENTE_2026_1,
        "visual": {
            "tipo": "tabla",
            "columnas": ["Grupo", "Característica", "Cantidad de formas"],
            "datos": [
                ["Grupo 1", "Tres hombres", "X"],
                ["Grupo 2", "Una mujer y dos hombres", "Y"],
                ["Grupo 3", "Dos mujeres y un hombre", "Z"],
                ["Grupo 4", "Tres mujeres", "W"],
            ],
        },
    },
    {
        "num_original": 5,
        "tema": "Tablas y multiplicación",
        "pregunta": "Un banco organizó un concurso para premiar a los usuarios que más utilizan las tarjetas de crédito. La tabla muestra el tipo de premio, la cantidad de premios que se entregó de cada tipo y el monto correspondiente a cada tipo de premio (Oro: 5 premios de $10.000.000 c/u; Plata: 25 premios de $5.000.000 c/u; Bronce: 100 premios de $1.000.000 c/u). ¿Cuál de las siguientes opciones muestra el total de dinero entregado por el banco para cada tipo de premio?",
        "opciones": [
            "Oro: $10.000.000 · Plata: $5.000.000 · Bronce: $1.000.000",
            "Oro: $50.000.000 · Plata: $125.000.000 · Bronce: $100.000.000",
            "Oro: $1.000.000.000 · Plata: $125.000.000 · Bronce: $5.000.000",
            "Oro: $50.000.000 · Plata: $100.000.000 · Bronce: $125.000.000",
        ],
        "correcta": "Oro: $50.000.000 · Plata: $125.000.000 · Bronce: $100.000.000",
        "fuente": FUENTE_2026_1,
        "visual": {
            "tipo": "tabla",
            "columnas": ["Tipo de premio", "Cantidad de premios", "Monto de cada premio"],
            "datos": [["Oro", 5, "$10.000.000"], ["Plata", 25, "$5.000.000"], ["Bronce", 100, "$1.000.000"]],
        },
    },
    {
        "num_original": 6,
        "tema": "Progresiones geométricas",
        "pregunta": "Los miembros de una familia deciden ahorrar dinero para comprar una bicicleta que cuesta $750.000. Acuerdan ahorrar $50.000 el primer mes y duplicar el ahorro cada mes hasta completar el valor de la bicicleta, siguiendo este procedimiento: Paso 1. Dividir $750.000 entre $50.000. Paso 2. Encontrar el valor de x tal que la suma de 2⁰ + 2¹ + ... + 2ˣ sea igual al resultado obtenido en el paso 1. Paso 3. Sumar 1 al valor de x encontrado en el paso 2. ¿Cuántos meses debe ahorrar la familia para comprar la bicicleta?",
        "opciones": ["16", "8", "4", "2"],
        "correcta": "4",
        "fuente": FUENTE_2026_1,
    },
    {
        "num_original": 7,
        "tema": "Porcentajes",
        "pregunta": "Alberto tiene un salario mensual de $800.000 y quiere ahorrar cada mes el 2 % de su sueldo, para lo cual ahorrará $16.000 mensuales. Estefanía quiere comprar una guitarra usando la misma estrategia que Alberto, pero ella tiene un sueldo mensual de $900.000 y quiere ahorrar cada mes el 3 %. Si Estefanía ahorra durante 10 meses consecutivos, ¿cuánto dinero ahorrará en total?",
        "opciones": ["$297.000", "$270.000", "$240.000", "$180.000"],
        "correcta": "$270.000",
        "fuente": FUENTE_2026_1,
    },
    {
        "num_original": 8,
        "tema": "Lectura y comparación de tablas y gráficas",
        "pregunta": "El DANE mide cada año la 'incidencia de la pobreza por el IPM' para algunas regiones de Colombia entre 2011 y 2015 (tabla). Al graficar esos mismos datos, ¿la información de la gráfica es la misma que la información presentada en la tabla?",
        "opciones": [
            "Sí, porque la información incluida en la gráfica es semejante a la información presentada en la tabla, para las regiones en mención.",
            "No, porque, en vez de graficar los datos de Antioquia, se graficaron los datos de la región Central.",
            "No, porque los datos de la gráfica de Antioquia para 2012 y 2013, y de Bogotá, D. C. para 2015, son diferentes a los datos presentados en la tabla.",
            "Sí, porque los datos de la gráfica de Antioquia para 2013 y de la región Central para 2012 corresponden a los datos presentados en la tabla.",
        ],
        "correcta": "No, porque los datos de la gráfica de Antioquia para 2012 y 2013, y de Bogotá, D. C. para 2015, son diferentes a los datos presentados en la tabla.",
        "fuente": FUENTE_2026_1,
        "visual": {
            "tipo": "grafico_lineas",
            "categorias": ["2011", "2012", "2013", "2014", "2015"],
            "series": {
                "Pacífica": [41.4, 36.3, 37.6, 34.6, 33.8],
                "Antioquia": [25.7, 21.7, 22.4, 19.5, 18.7],
                "Bogotá D.C.": [11.9, 11.1, 8.7, 5.4, 4.7],
                "Central": [30.7, 26.7, 26.1, 28.1, 22.1],
            },
        },
    },
    {
        "num_original": 9,
        "tema": "Interpretación de gráficos (distribuciones)",
        "pregunta": "Una máquina separa las 2.000 papas de un bulto de acuerdo con su peso p, obteniendo los datos de la tabla (15≤p<20: 700 papas; 20≤p<25: 500 papas; 25≤p<30: 800 papas). ¿Cuál de las siguientes opciones representa correctamente la distribución de las papas del bulto de acuerdo con su peso?",
        "opciones": [
            "Gráfico de pastel: 15-20 (35 %), 20-25 (25 %), 25-30 (40 %)",
            "Gráfico de pastel: los tres intervalos con 33,3 % cada uno",
            "Gráfico de barras: los tres intervalos con la misma altura (~5)",
            "Gráfico de barras: 15-20 con 700, 20-25 con 500, 25-30 con 800",
        ],
        "correcta": "Gráfico de barras: 15-20 con 700, 20-25 con 500, 25-30 con 800",
        "fuente": FUENTE_2026_1,
        "visual": {
            "tipo": "tabla",
            "columnas": ["Peso (gramos)", "Cantidad de papas"],
            "datos": [["15 ≤ p < 20", 700], ["20 ≤ p < 25", 500], ["25 ≤ p < 30", 800]],
        },
    },
    {
        "num_original": 10,
        "tema": "Muestreo estadístico",
        "pregunta": "Un candidato a la gobernación de un departamento quiere estimar el porcentaje de la población que votará por él. Contrata una firma encuestadora que escoge aleatoriamente un municipio del departamento y llama a 1.000 personas de ese lugar, preguntando su preferencia de voto. ¿Por qué el resultado de la encuesta puede diferir mucho de la realidad?",
        "opciones": [
            "Porque la única manera de obtener resultados precisos es encuestar a toda la población del departamento.",
            "Porque la encuesta solo representará la opinión de las personas del departamento, si el municipio escogido es el más grande.",
            "Porque de esta manera solo están tomándose en cuenta las opiniones de la población de un municipio del departamento.",
            "Porque la muestra es muy grande, lo cual permite que existan grandes diferencias entre las respuestas de las personas.",
        ],
        "correcta": "Porque la única manera de obtener resultados precisos es encuestar a toda la población del departamento.",
        "fuente": FUENTE_2026_1,
    },
    {
        "num_original": 11,
        "tema": "Área de figuras (composición de rectángulos)",
        "pregunta": "Una torta con forma rectangular, de 60 cm de base por 20 cm de altura, fue repartida entre 8 personas por medio de cortes rectos. Según la figura del cuadernillo, la pieza número 1 corresponde a un rectángulo de 15 cm por 15 cm en una de las esquinas del corte. Considerando la información anterior, ¿cuál es el área del trozo de torta número 1?",
        "opciones": ["225 cm²", "150 cm²", "75 cm²", "40 cm²"],
        "correcta": "225 cm²",
        "fuente": FUENTE_2026_1,
    },
    {
        "num_original": 12,
        "tema": "Unidades de medida",
        "pregunta": "La tabla muestra el peso de tres pedidos de mercancía que una empresa necesita enviar a otro país (Pedido 1: 500 kg; Pedido 2: 200 kg; Pedido 3: 1 ton). Para saber el costo total del envío, un empleado calcula: 500 + 200 + 1 = 701 ton. Esta solución es:",
        "opciones": [
            "incorrecta; el resultado debe estar dado en kg, ya que la mayoría de los valores están en esta unidad.",
            "correcta; se suman correctamente los tres valores y se utiliza una de las unidades de los pedidos.",
            "incorrecta; como los datos están en unidades diferentes, no pueden sumarse directamente.",
            "correcta; el resultado se calcula bien y la unidad utilizada corresponde a la unidad de mayor peso.",
        ],
        "correcta": "incorrecta; como los datos están en unidades diferentes, no pueden sumarse directamente.",
        "fuente": FUENTE_2026_1,
        "visual": {
            "tipo": "tabla",
            "columnas": ["Pedido", "Peso"],
            "datos": [["Pedido 1", "500 kg"], ["Pedido 2", "200 kg"], ["Pedido 3", "1 ton"]],
        },
    },
    {
        "num_original": 13,
        "tema": "Área de figuras compuestas",
        "pregunta": "Un pintor tiene un lienzo rectangular de 8 m × 5 m que quiere dividir en tres regiones: la región 1 (triangular, catetos 4 m y 3 m), la región 2 (un cuarto de círculo de radio 4 m) y la región 3 (el resto del lienzo). Para calcular el área de la región 3, el pintor: Paso 1. Calcula el área del lienzo (8×5). Paso 2. Calcula el área de la región 1 (multiplicando 3m×4m). Paso 3. Calcula el área de la región 2 (π×16 m² dividido entre 4). Paso 4. Al resultado del paso 1 le resta los resultados del paso 2 y el paso 3. ¿En cuál paso hay un error y cómo se puede corregir?",
        "opciones": [
            "En el paso 2, porque se debe multiplicar 3 m × 4 m × 5 m.",
            "En el paso 3, porque se debe multiplicar 2π × 4 m y luego dividir entre 4.",
            "En el paso 2, porque se debe multiplicar 4 m × 3 m y luego dividir entre 2.",
            "En el paso 3, porque se debe multiplicar π × 4 m y luego dividir entre 4.",
        ],
        "correcta": "En el paso 2, porque se debe multiplicar 4 m × 3 m y luego dividir entre 2.",
        "fuente": FUENTE_2026_1,
    },
    {
        "num_original": 14,
        "tema": "Relación entre tablas y gráficas",
        "pregunta": "En una encuesta sobre intención de voto para la elección de presidente en un país, se registraron los resultados en una tabla (Candidato E: 2.000 votos; F: 5.000; G: 4.500; H: 7.000; I: 3.400) y en una gráfica de pastel. De acuerdo con lo anterior, ¿cuál de las siguientes afirmaciones es falsa?",
        "opciones": [
            "Con la información de la tabla se obtienen los datos de la gráfica.",
            "Con la información de la gráfica se obtiene cuál es el candidato con mayor intención de voto.",
            "Con la información de la gráfica se obtienen los datos de la tabla.",
            "Con la información de la tabla se obtiene la proporción entre los votos por un candidato y el total.",
        ],
        "correcta": "Con la información de la gráfica se obtienen los datos de la tabla.",
        "fuente": FUENTE_2026_1,
        "visual": {
            "tipo": "tabla",
            "columnas": ["Candidato", "Votos"],
            "datos": [["E", 2000], ["F", 5000], ["G", 4500], ["H", 7000], ["I", 3400]],
        },
    },
    {
        "num_original": 15,
        "tema": "Tendencias e interpretación de tablas",
        "pregunta": "Un estudiante está ahorrando para un paseo que tiene un costo de $800.000; empezó su ahorro en enero con $100.000 que le regaló su abuela, y al final de cada mes está ahorrando cierta cantidad de dinero (tabla con el progreso del ahorro durante los primeros cuatro meses). ¿Cuál es la tendencia del dinero ahorrado al finalizar cada mes?",
        "opciones": ["Disminuye $30.000 cada mes.", "Aumenta $30.000 cada mes.", "Aumenta $100.000 cada mes.", "Disminuye $100.000 cada mes."],
        "correcta": "Aumenta $30.000 cada mes.",
        "fuente": FUENTE_2026_1,
        "visual": {
            "tipo": "tabla",
            "columnas": ["Mes", "Dinero ahorrado al inicio de mes", "Dinero ahorrado al finalizar el mes", "Dinero que hace falta para completar el ahorro"],
            "datos": [
                ["Enero", "$100.000", "$130.000", "$670.000"],
                ["Febrero", "$130.000", "$160.000", "$640.000"],
                ["Marzo", "$160.000", "$190.000", "$610.000"],
                ["Abril", "$190.000", "$220.000", "$580.000"],
            ],
        },
    },
    {
        "num_original": 16,
        "tema": "Promedio (media aritmética)",
        "pregunta": "La tabla muestra el registro que llevó un mecánico automotriz de las piezas que tuvieron que reemplazarse durante el mantenimiento de tres vehículos (Vehículo 1: 6 piezas; Vehículo 2: 5 piezas; Vehículo 3: 10 piezas). De acuerdo con esta información, ¿cuál es el promedio del número de piezas reemplazadas de los tres vehículos?",
        "opciones": ["21", "7", "10", "6"],
        "correcta": "7",
        "fuente": FUENTE_2026_1,
        "visual": {
            "tipo": "tabla",
            "columnas": ["Vehículo", "Número de piezas reemplazadas"],
            "datos": [[1, 6], [2, 5], [3, 10]],
        },
    },
    {
        "num_original": 17,
        "tema": "Diagramas de Venn",
        "pregunta": "La figura muestra la distribución de los tipos de transporte que utilizan 160 personas para llegar al trabajo (carro privado, bicicleta, transporte público), representada en un diagrama de Venn con las cantidades en cada región. Si se necesita saber la cantidad total de personas que se transportan en bicicleta, ¿cuáles son los datos que se deben sumar?",
        "opciones": ["5, 15, 20 y 25.", "5 y 20.", "25, 35 y 50.", "5, 20, 25 y 50."],
        "correcta": "5, 20, 25 y 50.",
        "fuente": FUENTE_2026_1,
        "visual": {
            "tipo": "tabla",
            "columnas": ["Región del diagrama de Venn", "Cantidad de personas"],
            "datos": [
                ["Solo carro privado", 35],
                ["Carro privado y bicicleta", 20],
                ["Solo bicicleta", 50],
                ["Carro privado y transporte público", 15],
                ["Los tres medios", 5],
                ["Solo transporte público", 10],
                ["Bicicleta y transporte público", 25],
            ],
        },
    },
    {
        "num_original": 18,
        "tema": "Crecimiento exponencial",
        "pregunta": "El fundador de una empresa de procesadores identificó que el número de transistores de un procesador tipo X se duplicó cada dos años. Si en el 2010 el procesador tipo X tenía 10.000 transistores, ¿cuántos transistores tenía el procesador tipo X en el 2016?",
        "opciones": ["20.000 transistores.", "40.000 transistores.", "60.000 transistores.", "80.000 transistores."],
        "correcta": "80.000 transistores.",
        "fuente": FUENTE_2026_1,
    },
    {
        "num_original": 19,
        "tema": "Área de figuras (razonamiento sobre procedimientos)",
        "pregunta": "Un jardín con forma cuadrada, de vértices EFGH, tiene lado x+y. Otro cuadrado de vértices PQRS está inscrito en el cuadrado EFGH, de tal manera que la distancia más cercana entre dos vértices consecutivos mide x. Para encontrar una fórmula del área de la región sombreada, el jardinero propuso: Paso 1. Escoger uno de los cuatro triángulos sombreados y multiplicar la altura por la base. Paso 2. Dividir entre 2 el resultado del paso 1. Paso 3. Multiplicar por 4 el resultado del paso anterior. Paso 4. Sumar cuatro veces el resultado del paso 2. De los pasos propuestos, ¿cuál es redundante para el cálculo del área de la región sombreada?",
        "opciones": [
            "El paso 4, porque al sumar cuatro veces el resultado del paso 2, se obtiene el resultado del paso 3.",
            "El paso 3, porque, al multiplicar por 4 el resultado obtenido en el paso 2, se obtiene el mismo resultado obtenido en el paso 1.",
            "El paso 2, porque, al dividir entre 2 el resultado del paso 1, se obtiene el mismo resultado del paso 3.",
            "El paso 1, porque, al multiplicar la altura de uno de los triángulos por la base, se obtiene el área total de la figura.",
        ],
        "correcta": "El paso 4, porque al sumar cuatro veces el resultado del paso 2, se obtiene el resultado del paso 3.",
        "fuente": FUENTE_2026_1,
    },
    {
        "num_original": 20,
        "tema": "Álgebra: factorización",
        "pregunta": "Al entrar a un túnel, un carro que lleva una velocidad de 10 m/s acelera a 3 m/s² durante 15 segundos, que es lo que dura recorriéndolo. La longitud del túnel se puede calcular mediante: (10 m/s)×(15s) + ½(3 m/s²)×(15s)². Al ver la fórmula, una persona afirma que esta es equivalente a: 15s × (10 m/s + ½(3 m/s²)). ¿Es verdadera la afirmación de la persona?",
        "opciones": [
            "Sí, porque lo que hizo fue factorizar el tiempo que tarda en recorrer el túnel.",
            "No, porque omitió que hay unos 15 segundos elevados al cuadrado.",
            "Sí, porque el exponente 2, al que está elevado el tiempo, se puede cancelar.",
            "No, porque también se tiene que factorizar el fraccionario 1/2.",
        ],
        "correcta": "No, porque omitió que hay unos 15 segundos elevados al cuadrado.",
        "fuente": FUENTE_2026_1,
    },
    {
        "num_original": 21,
        "tema": "Conversión de unidades y proporcionalidad",
        "pregunta": "Arturo quiere calcular el tiempo que se necesita para descargar un archivo de 12,6 megabytes. Sabe que la velocidad de descarga es 300 kilobytes por segundo, y que 1 megabyte equivale a 1.024 kilobytes. ¿Cuál de los siguientes procedimientos NO permite calcular el tiempo necesario para descargar el archivo?",
        "opciones": [
            "Paso 1. Multiplicar 12,6 por 1.024. Paso 2. Dividir el resultado del paso 1 entre 300.",
            "Paso 1. Multiplicar 1.024 por 300. Paso 2. Dividir el resultado del paso 1 entre 12,6.",
            "Paso 1. Dividir 12,6 entre 300. Paso 2. Multiplicar el resultado del paso 1 por 1.024.",
            "Paso 1. Dividir 1.024 entre 300. Paso 2. Multiplicar el resultado del paso 1 por 12,6.",
        ],
        "correcta": "Paso 1. Multiplicar 1.024 por 300. Paso 2. Dividir el resultado del paso 1 entre 12,6.",
        "fuente": FUENTE_2026_1,
    },
    {
        "num_original": 22,
        "tema": "Semejanza de triángulos",
        "pregunta": "Una persona construyó una rampa apoyada en un muro de 3 m de altura, que llega al suelo a 4 m del muro. Para evitar que la rampa se parta, se va a construir una columna de refuerzo a 2 m del muro. ¿Cuál de los siguientes procedimientos permite calcular la altura h que debe tener la columna?",
        "opciones": [
            "Paso 1. Dividir 2 m entre 4 m, obteniendo 0,5. Paso 2. Dividir 3 m entre el valor calculado en el paso 1.",
            "Paso 1. Dividir 4 m entre 2 m, obteniendo 0,5. Paso 2. Multiplicar 3 m por el valor calculado en el paso 1.",
            "Paso 1. Dividir 4 m entre 2 m, obteniendo 2. Paso 2. Dividir 3 m entre el valor calculado en el paso 1.",
            "Paso 1. Dividir 2 m entre 4 m, obteniendo 2. Paso 2. Multiplicar 3 m por el valor calculado en el paso 1.",
        ],
        "correcta": "Paso 1. Dividir 4 m entre 2 m, obteniendo 2. Paso 2. Dividir 3 m entre el valor calculado en el paso 1.",
        "fuente": FUENTE_2026_1,
        "visual": {
            "tipo": "figura_geometrica",
            "svg": "<svg viewBox='0 0 260 160' xmlns='http://www.w3.org/2000/svg'><rect x='14' y='20' width='12' height='120' fill='rgba(217,119,87,0.25)' stroke='#D97757' stroke-width='2'/><line x1='20' y1='20' x2='220' y2='140' stroke='#ECECE7' stroke-width='3'/><line x1='20' y1='140' x2='220' y2='140' stroke='#ECECE7' stroke-width='2'/><line x1='120' y1='140' x2='120' y2='80' stroke='#D97757' stroke-width='3'/><text x='2' y='85' fill='#ECECE7' font-size='13'>3 m</text><text x='55' y='155' fill='#ECECE7' font-size='13'>2 m</text><text x='128' y='115' fill='#D97757' font-size='13'>h</text><text x='195' y='155' fill='#ECECE7' font-size='13'>4 m</text></svg>",
        },
    },
    {
        "num_original": 23,
        "tema": "Coordenadas polares",
        "pregunta": "En una gráfica se muestra la ubicación, en coordenadas polares (r, θ), de cuatro aviones respecto a la torre de control de un aeropuerto: V (30 km, 30°), W (20 km, 90°), X (60 km, 180°), Y (40 km, 60°), donde r es la distancia al polo (la torre) y θ es el ángulo respecto al eje polar. ¿Cuál es el orden de los aviones, del que está más cerca al que está más lejos de la torre de control?",
        "opciones": ["W, V, Y, X.", "X, V, W, Y.", "V, Y, W, X.", "X, Y, V, W."],
        "correcta": "W, V, Y, X.",
        "fuente": FUENTE_2026_1,
    },
    {
        "num_original": 24,
        "tema": "Razonamiento aritmético (problema de recorrido)",
        "pregunta": "Kevin trabaja en una farmacia que entrega medicamentos a domicilio. El último viernes tuvo que entregar cuatro pedidos: para el primero avanzó 3 cuadras; para el segundo, avanzó el doble de cuadras que para el primero; para llegar al tercero, avanzó la mitad de cuadras que avanzó para el segundo; para el último, tuvo que regresarse 10 cuadras. Después de terminar las entregas, caminó una cuadra más para llegar a su casa. ¿Cuál de las siguientes operaciones permite obtener la distancia desde la farmacia hasta la casa de Kevin?",
        "opciones": ["3 + 3 + 3 − 10 + 1", "3 + 6 + 6 + 10", "3 + 6 + 3 − 10 + 1", "6 + 3 + 10 − 1"],
        "correcta": "3 + 6 + 3 − 10 + 1",
        "fuente": FUENTE_2026_1,
    },
    {
        "num_original": 25,
        "tema": "Ordenamiento de datos (números negativos)",
        "pregunta": "La presión pleural se genera entre algunas paredes de los pulmones en el proceso de respiración del ser humano. Se midió la presión pleural de cuatro pacientes (Santiago: −7,6; Ximena: −7,09; Mariana: −7,62; Orlando: −7,53 cmH₂O) para determinar el orden en que deben recibir un tratamiento pulmonar, ordenando de menor a mayor según su presión pleural. ¿Cuál es el orden correcto en que deben recibir el tratamiento los pacientes?",
        "opciones": [
            "Ximena, Mariana, Santiago, Orlando",
            "Orlando, Santiago, Mariana, Ximena",
            "Mariana, Santiago, Orlando, Ximena",
            "Santiago, Ximena, Mariana, Orlando",
        ],
        "correcta": "Mariana, Santiago, Orlando, Ximena",
        "fuente": FUENTE_2026_1,
        "visual": {
            "tipo": "tabla",
            "columnas": ["Paciente", "Presión pleural (cmH₂O)"],
            "datos": [["Santiago", -7.6], ["Ximena", -7.09], ["Mariana", -7.62], ["Orlando", -7.53]],
        },
    },
]
